// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'vacate_notice_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_VacateNoticeModel _$VacateNoticeModelFromJson(Map<String, dynamic> json) =>
    _VacateNoticeModel(
      id: json['id'] as String,
      reference: json['reference'] as String,
      occupationId: json['occupationId'] as String?,
      houseId: json['houseId'] as String?,
      houseCode: json['houseCode'] as String,
      houseNumber: json['houseNumber'] as String?,
      houseLabel: json['houseLabel'] as String?,
      propertyId: json['propertyId'] as String?,
      propertyName: json['propertyName'] as String?,
      estateId: json['estateId'] as String?,
      estateName: json['estateName'] as String?,
      tenantUserId: json['tenantUserId'] as String?,
      tenantName: json['tenantName'] as String,
      tenantPhone: json['tenantPhone'] as String?,
      tenantEmail: json['tenantEmail'] as String?,
      raisedBy: json['raisedBy'] as String?,
      raisedByName: json['raisedByName'] as String?,
      vacateDate: json['vacateDate'] as String?,
      reason: json['reason'] as String?,
      status: json['status'] as String,
      decidedByName: json['decidedByName'] as String?,
      decidedOn: json['decidedOn'] as String?,
      decisionNotes: json['decisionNotes'] as String?,
      rentOwed: parseDoubleNullable(json['rentOwed']),
      refundableDeposit: parseDoubleNullable(json['refundableDeposit']),
      totalDeductions: parseDoubleNullable(json['totalDeductions']),
      netAmount: parseDoubleNullable(json['netAmount']),
      settlementType: json['settlementType'] as String?,
      settled: json['settled'] as bool? ?? false,
      settledOn: json['settledOn'] as String?,
      paymentStatus: json['paymentStatus'] as String?,
      totalPaid: json['totalPaid'] == null ? 0 : parseDouble(json['totalPaid']),
      balanceRemaining: json['balanceRemaining'] == null
          ? 0
          : parseDouble(json['balanceRemaining']),
      refundConfirmed: json['refundConfirmed'] as bool? ?? false,
      refundReference: json['refundReference'] as String?,
      unpaidHandling: json['unpaidHandling'] as String?,
      unpaidNotes: json['unpaidNotes'] as String?,
      unpaidAmount: parseDoubleNullable(json['unpaidAmount']),
      processed: json['processed'] as bool? ?? false,
      processedOn: json['processedOn'] as String?,
      processedByName: json['processedByName'] as String?,
      daysToVacate: (json['daysToVacate'] as num?)?.toInt() ?? 0,
      nextStep: json['nextStep'] as String?,
      createdOn: json['createdOn'] as String?,
      updatedOn: json['updatedOn'] as String?,
    );

Map<String, dynamic> _$VacateNoticeModelToJson(_VacateNoticeModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'reference': instance.reference,
      'occupationId': instance.occupationId,
      'houseId': instance.houseId,
      'houseCode': instance.houseCode,
      'houseNumber': instance.houseNumber,
      'houseLabel': instance.houseLabel,
      'propertyId': instance.propertyId,
      'propertyName': instance.propertyName,
      'estateId': instance.estateId,
      'estateName': instance.estateName,
      'tenantUserId': instance.tenantUserId,
      'tenantName': instance.tenantName,
      'tenantPhone': instance.tenantPhone,
      'tenantEmail': instance.tenantEmail,
      'raisedBy': instance.raisedBy,
      'raisedByName': instance.raisedByName,
      'vacateDate': instance.vacateDate,
      'reason': instance.reason,
      'status': instance.status,
      'decidedByName': instance.decidedByName,
      'decidedOn': instance.decidedOn,
      'decisionNotes': instance.decisionNotes,
      'rentOwed': instance.rentOwed,
      'refundableDeposit': instance.refundableDeposit,
      'totalDeductions': instance.totalDeductions,
      'netAmount': instance.netAmount,
      'settlementType': instance.settlementType,
      'settled': instance.settled,
      'settledOn': instance.settledOn,
      'paymentStatus': instance.paymentStatus,
      'totalPaid': instance.totalPaid,
      'balanceRemaining': instance.balanceRemaining,
      'refundConfirmed': instance.refundConfirmed,
      'refundReference': instance.refundReference,
      'unpaidHandling': instance.unpaidHandling,
      'unpaidNotes': instance.unpaidNotes,
      'unpaidAmount': instance.unpaidAmount,
      'processed': instance.processed,
      'processedOn': instance.processedOn,
      'processedByName': instance.processedByName,
      'daysToVacate': instance.daysToVacate,
      'nextStep': instance.nextStep,
      'createdOn': instance.createdOn,
      'updatedOn': instance.updatedOn,
    };
